service: infra

frameworkVersion: '3'

configValidationMode: warn
useDotenv: true

provider:
  name: aws
  region: ap-northeast-1
  profile: default
  runtime: ruby2.7
  timeout: 60
  memorySize: 128
  logRetentionInDays: 1
  versionFunctions: false
  architecture: x86_64

functions:
  billing-notify-batch :
    handler: handler.rb
    events:
      - schedule: cron(0 12 * * ? *)
